### ISSUE TITLE
No file name gallerydeluxe/init.html

### ISSUE THREAD

**Issue by guinslym** [bep/galleriesdeluxe#8]
There is no fille [gallerydeluxe/init.html](https://github.com/bep/galleriesdeluxe/blob/622d8268efc34179def10419903d0742d72a0684/layouts/partials/galleriesdeluxe/list-gallery.html#L2)

in list-gallery.html

`  {{ $gallery := partial "gallerydeluxe/init.html" (dict "images" .images) }}`

`Error: error building site: render: failed to render pages: render of "page" failed: "/Users/guinslym/Documents/coding/quickstart/themes/gallerydeluxe/layouts/_default/single.html:2:5": execute of template failed: template: _default/single.html:2:5: executing "main" at <partial "galleriesdeluxe/list-gallery.html" .>: error calling partial: "/Users/guinslym/Documents/coding/quickstart/themes/gallerydeluxe/layouts/partials/galleriesdeluxe/list-gallery.html:2:17": execute of template failed: template: partials/galleriesdeluxe/list-gallery.html:2:17: executing "partials/galleriesdeluxe/list-gallery.html" at <partial "gallerydeluxe/init.html" (dict "images" .images)>: error calling partial: partial "gallerydeluxe/init.html" not found`

**Comment by bep** [comment]
This repo needs to be built with Hugo Modules (as in, you need Go installed). If you have Go installed, you should be able to cd into exampleSite and run `hugo server`. 

I suspect you will get faster help if you ask questions at https://discourse.gohugo.io/
